config/routes.rb
Rails.application.routes.draw do
  resources :notes
  devise_for :users, controllers: {registrations: 'users/registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "notes#index"
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings

  validates_presence_of :title
  validates_presence_of :body
  validates_presence_of :user_id

  enum priority: { none: 0, low: 1, medium: 2, critical: 3 }, _prefix: true

  PRIORITY_COLOR_SCHEME = { none: 'black', low: 'grey', medium: 'orange', critical: 'red' }

  def tag_list=(names)
  	self.tags = names.split(',').map do |tag_text|
  	  Tag.where(text: tag_text.strip).first_or_create
  	end
  end

  def tag_list
  	tags.pluck(:text).join(',')
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :check_user_signed_in?
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = current_user.notes
    @notes = @notes#.where(active: true)
    if params[:tag_id].present?
      @notes = @notes.joins(:taggings).where(taggings: { tag_id: params[:tag_id] })
    end
    @notes = case params[:status]
             when 'active', nil
               @notes.where(active: true)
             when 'inactive'
               @notes.where(active: false)
             else
               @notes
             end
    if params[:order_by].present?
      @notes = @notes.order("#{params[:order_by]} #{params[:direction]}")
    else
      @notes = @notes.order(updated_at: :desc)
    end
    @notes = @notes.paginate(page: params[:page], per_page: 10)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_path, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to notes_path, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.fetch(:note, {}).permit(:title, :body, :user_id, :tag_list, :priority, :active)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <div class='form-group'>
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, placeholder: 'Enter title', class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_area :body, placeholder: 'Enter some content', class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= form.label :tags, class: 'form-label' %>
    <%= form.text_field :tag_list, placeholder: 'Enter comma separated tags', class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= form.label :priority, class: 'form-label' %>
    <%= form.select :priority, options_for_select(Note.priorities.collect{|v| [v[0].humanize, v[0]]}, selected: note.priority), {}, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= form.label :active, class: 'form-label' %>
    <%= form.check_box :active, class: '' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<br><br>
<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice" class='notice'><%= notice %></p>

<div class='row'>
  <div class='col-md-2 col-sm-2 col-lg-2 col-xs-2'>
    <%= button_to 'Add a New Note', new_note_path, class: 'btn-primary btn', method: 'get' %>
  </div>
  <div class='col-md-8 col-sm-8 col-lg-8 col-xs-8'>
    
  </div>
  <div class='col-md-2 col-sm-2 col-lg-2 col-xs-2'>
    <%= select_tag :status, options_for_select(['active', 'inactive', 'all'], params[:status] || 'active'), class: 'form-control', data: { notes_path: notes_path } %>
  </div>
</div>
<br>

<%= will_paginate @notes %>

<div class='table-responsive table-hover'>
  <table class='table table-hover' style='width: 100% !important'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th>Tags</th>
        <th><%= link_to 'Priority', notes_path(order_by: 'priority', direction: (params[:order_by] == 'priority' && params[:direction] == 'asc') ? 'desc' : 'asc') %></th>
        <th>Status</th>
        <th colspan='2'></th>
      </tr>
    </thead>

    <tbody>
      <% @notes.each do |note| %>
        <tr style="cursor: pointer; color: <%= note.active? ? '' : 'grey'; %>" data-toggle='modal' data-target='#noteModal'>
          <td><%= link_to note.title, note_path(note) %></td>
          <td><%= note.body.truncate(25) %></td>
          <td>
            <%= note.tags.map{|tag| link_to tag.text.strip, notes_path(tag_id: tag.id) }.join(', ').html_safe %>
          </td>
          <td style="color: <%= Note::PRIORITY_COLOR_SCHEME[note.priority.to_sym] %>"><%= note.priority %></td>
          <td><%= note.active? ? 'Active' : 'Inactive' %></td>
          <td><%= link_to 'Edit', edit_note_path(note) %></td>
          <td>
            <% if note.active? %>
              <%= button_to 'Deactivate', note_path(note, note: {active: false}), method: :put, class: 'btn btn-danger btn-sm' %>
            <% else %>
              <%= button_to 'Activate', note_path(note, note: {active: true}), method: :put, class: 'btn btn-success btn-sm' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= javascript_pack_tag :notes %>
<br>

app/views/notes/new.html.erb
<br>
<br>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center">
  <h1 class=''><%= @note.title %></h1>
  <h5><%= @note.tags.map{|tag| link_to tag.text.strip, notes_path(tag_id: tag.id) }.join(', ').html_safe %></h5>
  <div class='card flex'>
  	<%= @note.body %>
  </div>
</div>
<br>
<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>